import { afterEach, beforeEach, describe, expect, spyOn, test } from "bun:test";

import { resetAuthCache } from "./github-auth.js";
import * as githubClient from "./github-client.js";
import { registerReleaseCreateTool } from "./release-create-tool.js";
import { captureTool } from "./test-harness.js";

describe("release_create", () => {
  const run = captureTool(registerReleaseCreateTool);
  const originalGithubToken = process.env.GITHUB_TOKEN;

  beforeEach(() => {
    process.env.GITHUB_TOKEN = "test-token";
    resetAuthCache();
  });

  afterEach(() => {
    if (originalGithubToken === undefined) {
      delete process.env.GITHUB_TOKEN;
    } else {
      process.env.GITHUB_TOKEN = originalGithubToken;
    }
    resetAuthCache();
  });

  test("creates a release with explicit fields", async () => {
    let request:
      | Parameters<ReturnType<typeof githubClient.getOctokit>["repos"]["createRelease"]>[0]
      | undefined;
    const spy = spyOn(githubClient, "getOctokit").mockReturnValue({
      repos: {
        createRelease: async (params) => {
          request = params;
          return {
            data: {
              html_url: "https://github.com/Rethunk-AI/test-repo/releases/tag/v1.0.0",
              id: 123,
              tag_name: params.tag_name,
              draft: params.draft ?? false,
              prerelease: params.prerelease ?? false,
            },
          };
        },
      },
    } as unknown as ReturnType<typeof githubClient.getOctokit>);

    const parsed = JSON.parse(
      await run({
        owner: "Rethunk-AI",
        repo: "test-repo",
        tag: "v1.0.0",
        name: "Release 1.0.0",
        body: "Initial release",
        draft: true,
        prerelease: false,
        generateNotes: false,
      }),
    ) as {
      url: string;
      id: number;
      tag: string;
      draft: boolean;
      prerelease: boolean;
    };

    expect(request).toMatchObject({
      owner: "Rethunk-AI",
      repo: "test-repo",
      tag_name: "v1.0.0",
      name: "Release 1.0.0",
      body: "Initial release",
      draft: true,
      prerelease: false,
      generate_release_notes: false,
    });
    expect(parsed).toEqual({
      url: "https://github.com/Rethunk-AI/test-repo/releases/tag/v1.0.0",
      id: 123,
      tag: "v1.0.0",
      draft: true,
      prerelease: false,
    });

    spy.mockRestore();
  });

  test("delegates autogenerated notes to GitHub", async () => {
    let request:
      | Parameters<ReturnType<typeof githubClient.getOctokit>["repos"]["createRelease"]>[0]
      | undefined;
    const spy = spyOn(githubClient, "getOctokit").mockReturnValue({
      repos: {
        createRelease: async (params) => {
          request = params;
          return {
            data: {
              html_url: "https://github.com/Rethunk-AI/test-repo/releases/tag/v1.2.3",
              id: 456,
              tag_name: params.tag_name,
              draft: false,
              prerelease: false,
            },
          };
        },
      },
    } as unknown as ReturnType<typeof githubClient.getOctokit>);

    await run({
      owner: "Rethunk-AI",
      repo: "test-repo",
      tag: "v1.2.3",
      generateNotes: true,
    });

    expect(request).toMatchObject({
      tag_name: "v1.2.3",
      name: "v1.2.3",
      body: "",
      generate_release_notes: true,
    });

    spy.mockRestore();
  });

  test("maps GitHub validation errors to structured envelopes", async () => {
    const spy = spyOn(githubClient, "getOctokit").mockReturnValue({
      repos: {
        createRelease: async () => {
          throw { status: 422, message: "Validation failed" };
        },
      },
    } as unknown as ReturnType<typeof githubClient.getOctokit>);

    const parsed = JSON.parse(
      await run({
        owner: "Rethunk-AI",
        repo: "test-repo",
        tag: "v1.0.0",
      }),
    ) as { error: { code: string; message: string } };

    expect(parsed.error.code).toBe("VALIDATION");
    expect(parsed.error.message).toBe("Validation failed");

    spy.mockRestore();
  });
});
